version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    environment:
      - NGINX_BACKEND_HOST=http://localhost:3001
    ports:
      - 8083:80
    logging:
      driver: "json-file"
      options:
        max-size: "40m"
        max-file: "5"
    restart: always
    tty: true

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      - DB_PG_HOST=localhost:5432
    ports:
      - 3001:3000
    logging:
      driver: "json-file"
      options:
        max-size: "40m"
        max-file: "5"
    restart: always
    tty: true